version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
  py27: &py27
    image: asgirabbitmq_py27
    build:
      context: .
      dockerfile: compose/py27
    command: tox
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py27-django111
  py27dj111:
    <<: *py27
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py27-django111
  py38dj111:
    <<: *py38
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py38-django111
  py38dj30:
    <<: *py38
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py38-django30
  py38dj31:
    <<: *py38
    environment:
      RABBITMQ_HOST: rabbitmq
      TOXENV: py38-django31
